# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Geographic HLA allele frequency data for region-weighted vaccine design.

Provides curated per-region HLA class I allele frequencies drawn from
population-level studies and bone marrow registries, along with 2024
estimated regional populations.  These data support region-weighted
coverage calculations when selecting peptide-vaccine allele panels.
"""

from __future__ import annotations

import pandas as pd

REGION_PRIORITY_ROWS: list[dict] = [
    {
        "region": "Europe",
        "proxy": "Italy donor registry",
        "locus": "A",
        "allele": "HLA-A*02:01",
        "frequency": 0.2280,
        "resolution": "exact",
        "source_label": "Italian Bone Marrow Donor Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6771744/",
        "note": "Top European proxy allele.",
    },
    {
        "region": "Europe",
        "proxy": "Italy donor registry",
        "locus": "A",
        "allele": "HLA-A*24:02",
        "frequency": 0.1230,
        "resolution": "exact",
        "source_label": "Italian Bone Marrow Donor Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6771744/",
        "note": "Top European proxy allele.",
    },
    {
        "region": "Europe",
        "proxy": "Italy donor registry",
        "locus": "A",
        "allele": "HLA-A*01:01",
        "frequency": 0.1150,
        "resolution": "exact",
        "source_label": "Italian Bone Marrow Donor Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6771744/",
        "note": "Top European proxy allele.",
    },
    {
        "region": "Europe",
        "proxy": "Italy donor registry",
        "locus": "B",
        "allele": "HLA-B*51:01",
        "frequency": 0.0980,
        "resolution": "exact",
        "source_label": "Italian Bone Marrow Donor Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6771744/",
        "note": "Top European proxy allele.",
    },
    {
        "region": "Europe",
        "proxy": "Italy donor registry",
        "locus": "B",
        "allele": "HLA-B*18:01",
        "frequency": 0.0950,
        "resolution": "exact",
        "source_label": "Italian Bone Marrow Donor Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6771744/",
        "note": "Top European proxy allele.",
    },
    {
        "region": "Europe",
        "proxy": "Italy donor registry",
        "locus": "B",
        "allele": "HLA-B*35:01",
        "frequency": 0.0800,
        "resolution": "exact",
        "source_label": "Italian Bone Marrow Donor Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6771744/",
        "note": "Representative B*35 family allele.",
    },
    {
        "region": "Europe",
        "proxy": "Italy donor registry",
        "locus": "C",
        "allele": "HLA-C*04:01",
        "frequency": 0.1750,
        "resolution": "exact",
        "source_label": "Italian Bone Marrow Donor Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6771744/",
        "note": "Top European proxy allele.",
    },
    {
        "region": "Europe",
        "proxy": "Italy donor registry",
        "locus": "C",
        "allele": "HLA-C*07:01",
        "frequency": 0.1710,
        "resolution": "exact",
        "source_label": "Italian Bone Marrow Donor Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6771744/",
        "note": "Top European proxy allele.",
    },
    {
        "region": "Europe",
        "proxy": "Italy donor registry",
        "locus": "C",
        "allele": "HLA-C*06:02",
        "frequency": 0.0990,
        "resolution": "exact",
        "source_label": "Italian Bone Marrow Donor Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6771744/",
        "note": "Top European proxy allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "A",
        "allele": "HLA-A*02:01",
        "frequency": 0.1589,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Top Arab proxy allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "A",
        "allele": "HLA-A*24:02",
        "frequency": 0.0937,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Top Arab proxy allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "A",
        "allele": "HLA-A*01:01",
        "frequency": 0.0773,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Top Arab proxy allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "A",
        "allele": "HLA-A*11:01",
        "frequency": 0.0648,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Common Arab allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "A",
        "allele": "HLA-A*68:01",
        "frequency": 0.0579,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Common Arab allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "B",
        "allele": "HLA-B*50:01",
        "frequency": 0.1202,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Top Arab-specific B allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "B",
        "allele": "HLA-B*51:01",
        "frequency": 0.1049,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Top Arab proxy allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "B",
        "allele": "HLA-B*08:01",
        "frequency": 0.0723,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Common Arab allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "B",
        "allele": "HLA-B*40:06",
        "frequency": 0.0361,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Important South Asia / Arab overlap allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "B",
        "allele": "HLA-B*58:01",
        "frequency": 0.0319,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Common Arab allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "C",
        "allele": "HLA-C*06:02",
        "frequency": 0.1396,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Top Arab proxy allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "C",
        "allele": "HLA-C*04:01",
        "frequency": 0.1320,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Top Arab proxy allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "C",
        "allele": "HLA-C*07:02",
        "frequency": 0.1289,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Top Arab proxy allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "C",
        "allele": "HLA-C*15:02",
        "frequency": 0.0920,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Common Arab allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "C",
        "allele": "HLA-C*07:01",
        "frequency": 0.0729,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Common Arab allele.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "C",
        "allele": "HLA-C*17:01",
        "frequency": 0.0538,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "MENA allele worth considering in an extended panel.",
    },
    {
        "region": "MENA / Arab",
        "proxy": "Kuwait",
        "locus": "C",
        "allele": "HLA-C*12:03",
        "frequency": 0.0513,
        "resolution": "exact",
        "source_label": "Kuwaiti population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7024892/",
        "note": "Common Arab allele.",
    },
    {
        "region": "East Asia",
        "proxy": "Yunnan Han",
        "locus": "A",
        "allele": "HLA-A*11:01",
        "frequency": 0.2680,
        "resolution": "exact",
        "source_label": "Yunnan Han population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4068047/",
        "note": "Top East Asian A allele.",
    },
    {
        "region": "East Asia",
        "proxy": "Yunnan Han",
        "locus": "A",
        "allele": "HLA-A*24:02",
        "frequency": 0.1900,
        "resolution": "exact",
        "source_label": "Yunnan Han population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4068047/",
        "note": "Top East Asian A allele.",
    },
    {
        "region": "East Asia",
        "proxy": "Yunnan Han",
        "locus": "A",
        "allele": "HLA-A*02:07",
        "frequency": 0.0940,
        "resolution": "exact",
        "source_label": "Yunnan Han population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4068047/",
        "note": "East Asia-enriched A allele commonly missed in European-centric panels.",
    },
    {
        "region": "East Asia",
        "proxy": "Yunnan Han",
        "locus": "A",
        "allele": "HLA-A*02:01",
        "frequency": 0.0860,
        "resolution": "exact",
        "source_label": "Yunnan Han population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4068047/",
        "note": "Common East Asian A allele.",
    },
    {
        "region": "East Asia",
        "proxy": "Yunnan Han",
        "locus": "A",
        "allele": "HLA-A*02:06",
        "frequency": 0.0520,
        "resolution": "exact",
        "source_label": "Yunnan Han population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4068047/",
        "note": "Common East Asian A allele.",
    },
    {
        "region": "East Asia",
        "proxy": "Yunnan Han",
        "locus": "A",
        "allele": "HLA-A*02:03",
        "frequency": 0.0400,
        "resolution": "exact",
        "source_label": "Yunnan Han population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4068047/",
        "note": "Common East Asian A allele.",
    },
    {
        "region": "East Asia",
        "proxy": "Yunnan Han",
        "locus": "B",
        "allele": "HLA-B*46:01",
        "frequency": 0.1440,
        "resolution": "exact",
        "source_label": "Yunnan Han population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4068047/",
        "note": "Major East Asian B allele excluded from most European-focused work.",
    },
    {
        "region": "East Asia",
        "proxy": "Yunnan Han",
        "locus": "B",
        "allele": "HLA-B*40:01",
        "frequency": 0.1170,
        "resolution": "exact",
        "source_label": "Yunnan Han population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4068047/",
        "note": "Top East Asian B allele.",
    },
    {
        "region": "East Asia",
        "proxy": "Yunnan Han",
        "locus": "B",
        "allele": "HLA-B*13:01",
        "frequency": 0.0840,
        "resolution": "exact",
        "source_label": "Yunnan Han population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4068047/",
        "note": "Common East Asian B allele not in most compact panels.",
    },
    {
        "region": "East Asia",
        "proxy": "Yunnan Han",
        "locus": "C",
        "allele": "HLA-C*01:02",
        "frequency": 0.2030,
        "resolution": "exact",
        "source_label": "Yunnan Han population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4068047/",
        "note": "Major East Asian C allele excluded from most European-focused panels.",
    },
    {
        "region": "East Asia",
        "proxy": "Yunnan Han",
        "locus": "C",
        "allele": "HLA-C*07:02",
        "frequency": 0.1530,
        "resolution": "exact",
        "source_label": "Yunnan Han population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4068047/",
        "note": "Common East Asian C allele.",
    },
    {
        "region": "East Asia",
        "proxy": "Yunnan Han",
        "locus": "C",
        "allele": "HLA-C*03:04",
        "frequency": 0.1170,
        "resolution": "exact",
        "source_label": "Yunnan Han population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4068047/",
        "note": "Common East Asian C allele.",
    },
    {
        "region": "East Asia",
        "proxy": "Singapore Chinese",
        "locus": "A",
        "allele": "HLA-A*11:01",
        "frequency": 0.2827,
        "resolution": "exact",
        "source_label": "Singapore Chinese donors",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9873421/",
        "note": "Independent East Asian validation of A*11:01 dominance.",
    },
    {
        "region": "East Asia",
        "proxy": "Singapore Chinese",
        "locus": "B",
        "allele": "HLA-B*40:01",
        "frequency": 0.1916,
        "resolution": "exact",
        "source_label": "Singapore Chinese donors",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9873421/",
        "note": "Independent East Asian validation of B*40:01.",
    },
    {
        "region": "East Asia",
        "proxy": "Singapore Chinese",
        "locus": "C",
        "allele": "HLA-C*07:02",
        "frequency": 0.1996,
        "resolution": "exact",
        "source_label": "Singapore Chinese donors",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9873421/",
        "note": "Independent East Asian validation of C*07:02.",
    },
    {
        "region": "Southeast Asia",
        "proxy": "Thailand",
        "locus": "A",
        "allele": "HLA-A*11:01",
        "frequency": 0.2606,
        "resolution": "exact",
        "source_label": "Thai population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7057685/",
        "note": "Top Southeast Asian A allele.",
    },
    {
        "region": "Southeast Asia",
        "proxy": "Thailand",
        "locus": "B",
        "allele": "HLA-B*46:01",
        "frequency": 0.1404,
        "resolution": "exact",
        "source_label": "Thai population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7057685/",
        "note": "Top Southeast Asian B allele.",
    },
    {
        "region": "Southeast Asia",
        "proxy": "Thailand",
        "locus": "B",
        "allele": "HLA-B*15:02",
        "frequency": 0.0766,
        "resolution": "exact",
        "source_label": "Thai population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7057685/",
        "note": "Major Southeast Asian B allele often missed in compact global panels.",
    },
    {
        "region": "Southeast Asia",
        "proxy": "Thailand",
        "locus": "B",
        "allele": "HLA-B*40:01",
        "frequency": 0.0660,
        "resolution": "exact",
        "source_label": "Thai population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7057685/",
        "note": "Common Southeast Asian B allele.",
    },
    {
        "region": "Southeast Asia",
        "proxy": "Thailand",
        "locus": "B",
        "allele": "HLA-B*58:01",
        "frequency": 0.0638,
        "resolution": "exact",
        "source_label": "Thai population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7057685/",
        "note": "Common Southeast Asian B allele.",
    },
    {
        "region": "Southeast Asia",
        "proxy": "Thailand",
        "locus": "C",
        "allele": "HLA-C*01:02",
        "frequency": 0.1713,
        "resolution": "exact",
        "source_label": "Thai population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7057685/",
        "note": "Top Southeast Asian C allele.",
    },
    {
        "region": "Southeast Asia",
        "proxy": "Thailand",
        "locus": "C",
        "allele": "HLA-C*07:02",
        "frequency": 0.1191,
        "resolution": "exact",
        "source_label": "Thai population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7057685/",
        "note": "Common Southeast Asian C allele.",
    },
    {
        "region": "Southeast Asia",
        "proxy": "Thailand",
        "locus": "C",
        "allele": "HLA-C*08:01",
        "frequency": 0.1032,
        "resolution": "exact",
        "source_label": "Thai population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7057685/",
        "note": "Important Southeast Asian C allele not in compact baseline panels.",
    },
    {
        "region": "Southeast Asia",
        "proxy": "Singapore Malay",
        "locus": "A",
        "allele": "HLA-A*11:01",
        "frequency": 0.1804,
        "resolution": "exact",
        "source_label": "Singapore Malay donors",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9873421/",
        "note": "Independent Southeast Asian validation of A*11:01.",
    },
    {
        "region": "Southeast Asia",
        "proxy": "Singapore Malay",
        "locus": "B",
        "allele": "HLA-B*15:02",
        "frequency": 0.1148,
        "resolution": "exact",
        "source_label": "Singapore Malay donors",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9873421/",
        "note": "Independent Southeast Asian validation of B*15:02.",
    },
    {
        "region": "Southeast Asia",
        "proxy": "Singapore Malay",
        "locus": "C",
        "allele": "HLA-C*08:01",
        "frequency": 0.2008,
        "resolution": "exact",
        "source_label": "Singapore Malay donors",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9873421/",
        "note": "Independent Southeast Asian validation of C*08:01.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "A",
        "allele": "HLA-A*01:01",
        "frequency": 0.2541,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for dominant HLA-A*01 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "A",
        "allele": "HLA-A*02:01",
        "frequency": 0.2483,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for dominant HLA-A*02 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "A",
        "allele": "HLA-A*11:01",
        "frequency": 0.1753,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for dominant HLA-A*11 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "A",
        "allele": "HLA-A*24:02",
        "frequency": 0.1027,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for HLA-A*24 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "A",
        "allele": "HLA-A*03:01",
        "frequency": 0.0907,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for HLA-A*03 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "B",
        "allele": "HLA-B*35:01",
        "frequency": 0.2054,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for HLA-B*35 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "B",
        "allele": "HLA-B*15:01",
        "frequency": 0.1536,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for HLA-B*15 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "B",
        "allele": "HLA-B*40:01",
        "frequency": 0.1359,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for HLA-B*40 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "B",
        "allele": "HLA-B*07:02",
        "frequency": 0.1014,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for HLA-B*07 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "B",
        "allele": "HLA-B*44:02",
        "frequency": 0.0779,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for HLA-B*44 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "C",
        "allele": "HLA-C*07:02",
        "frequency": 0.2806,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for HLA-C*07 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "C",
        "allele": "HLA-C*04:01",
        "frequency": 0.2042,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for HLA-C*04 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "C",
        "allele": "HLA-C*03:04",
        "frequency": 0.1555,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for HLA-C*03 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "C",
        "allele": "HLA-C*06:02",
        "frequency": 0.1304,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for HLA-C*06 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "North India",
        "locus": "C",
        "allele": "HLA-C*12:03",
        "frequency": 0.0527,
        "resolution": "proxy_group",
        "source_label": "North Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12392222/",
        "note": "Representative high-resolution allele for HLA-C*12 antigen group.",
    },
    {
        "region": "South Asia",
        "proxy": "Singapore Indians",
        "locus": "A",
        "allele": "HLA-A*24:02",
        "frequency": 0.1659,
        "resolution": "exact",
        "source_label": "Singapore Indian donors",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9873421/",
        "note": "Independent South Asian proxy allele.",
    },
    {
        "region": "South Asia",
        "proxy": "Singapore Indians",
        "locus": "B",
        "allele": "HLA-B*40:06",
        "frequency": 0.1008,
        "resolution": "exact",
        "source_label": "Singapore Indian donors",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9873421/",
        "note": "South Asia-enriched B allele usually absent from European-centric panels.",
    },
    {
        "region": "South Asia",
        "proxy": "Singapore Indians",
        "locus": "C",
        "allele": "HLA-C*06:02",
        "frequency": 0.1396,
        "resolution": "exact",
        "source_label": "Singapore Indian donors",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9873421/",
        "note": "Independent South Asian proxy allele.",
    },
    {
        "region": "South Asia",
        "proxy": "17th IHIW Indian cohort",
        "locus": "A",
        "allele": "HLA-A*01:01",
        "frequency": 0.1650,
        "resolution": "exact",
        "source_label": "17th IHIW Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8315142/",
        "note": "India-specific A allele frequency reported in global workshop summary.",
    },
    {
        "region": "South Asia",
        "proxy": "17th IHIW Indian cohort",
        "locus": "A",
        "allele": "HLA-A*02:11",
        "frequency": 0.0710,
        "resolution": "exact",
        "source_label": "17th IHIW Indian population",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8315142/",
        "note": "South Asia-specific A allele elevated in Asian Indians.",
    },
    {
        "region": "Sub-Saharan Africa",
        "proxy": "Free State African descent",
        "locus": "A",
        "allele": "HLA-A*30:01",
        "frequency": 0.1310,
        "resolution": "proxy_group",
        "source_label": "Free State African descent group",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8085688/",
        "note": "Representative high-resolution allele for HLA-A*30 group.",
    },
    {
        "region": "Sub-Saharan Africa",
        "proxy": "Free State African descent",
        "locus": "A",
        "allele": "HLA-A*68:02",
        "frequency": 0.1280,
        "resolution": "proxy_group",
        "source_label": "Free State African descent group",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8085688/",
        "note": "Representative high-resolution allele for HLA-A*68 group.",
    },
    {
        "region": "Sub-Saharan Africa",
        "proxy": "Free State African descent",
        "locus": "A",
        "allele": "HLA-A*02:01",
        "frequency": 0.1230,
        "resolution": "proxy_group",
        "source_label": "Free State African descent group",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8085688/",
        "note": "Representative high-resolution allele for HLA-A*02 group.",
    },
    {
        "region": "Sub-Saharan Africa",
        "proxy": "Free State African descent",
        "locus": "B",
        "allele": "HLA-B*15:03",
        "frequency": 0.1260,
        "resolution": "proxy_group",
        "source_label": "Free State African descent group",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8085688/",
        "note": "Representative SSA-focused allele for dominant HLA-B*15 group.",
    },
    {
        "region": "Sub-Saharan Africa",
        "proxy": "Free State African descent",
        "locus": "B",
        "allele": "HLA-B*58:02",
        "frequency": 0.1170,
        "resolution": "proxy_group",
        "source_label": "Free State African descent group",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8085688/",
        "note": "Representative SSA-focused allele for dominant HLA-B*58 group.",
    },
    {
        "region": "Sub-Saharan Africa",
        "proxy": "Free State African descent",
        "locus": "B",
        "allele": "HLA-B*44:03",
        "frequency": 0.0990,
        "resolution": "proxy_group",
        "source_label": "Free State African descent group",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8085688/",
        "note": "Representative high-resolution allele for HLA-B*44 group.",
    },
    {
        "region": "Sub-Saharan Africa",
        "proxy": "Free State African descent",
        "locus": "C",
        "allele": "HLA-C*07:02",
        "frequency": 0.1680,
        "resolution": "proxy_group",
        "source_label": "Free State African descent group",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8085688/",
        "note": "Representative high-resolution allele for HLA-C*07 group.",
    },
    {
        "region": "Sub-Saharan Africa",
        "proxy": "Free State African descent",
        "locus": "C",
        "allele": "HLA-C*06:02",
        "frequency": 0.1640,
        "resolution": "proxy_group",
        "source_label": "Free State African descent group",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8085688/",
        "note": "Representative high-resolution allele for HLA-C*06 group.",
    },
    {
        "region": "Sub-Saharan Africa",
        "proxy": "Free State African descent",
        "locus": "C",
        "allele": "HLA-C*04:01",
        "frequency": 0.1280,
        "resolution": "proxy_group",
        "source_label": "Free State African descent group",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC8085688/",
        "note": "Representative high-resolution allele for HLA-C*04 group.",
    },
    {
        "region": "Sub-Saharan Africa",
        "proxy": "South African Bone Marrow Registry",
        "locus": "B",
        "allele": "HLA-B*07:02",
        "frequency": 0.0820,
        "resolution": "exact",
        "source_label": "South African Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5937380/",
        "note": "Exact SSA registry allele.",
    },
    {
        "region": "Sub-Saharan Africa",
        "proxy": "South African Bone Marrow Registry",
        "locus": "C",
        "allele": "HLA-C*07:02",
        "frequency": 0.1800,
        "resolution": "exact",
        "source_label": "South African Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC5937380/",
        "note": "Exact SSA registry allele.",
    },
    {
        "region": "Sub-Saharan Africa",
        "proxy": "Southern African review",
        "locus": "A",
        "allele": "HLA-A*74:01",
        "frequency": None,
        "resolution": "qualitative",
        "source_label": "Southern African perspective review",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4549606/",
        "note": "African-enriched allele highlighted as underrepresented outside SSA studies.",
    },
    {
        "region": "Sub-Saharan Africa",
        "proxy": "Southern African review",
        "locus": "B",
        "allele": "HLA-B*57:03",
        "frequency": None,
        "resolution": "qualitative",
        "source_label": "Southern African perspective review",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4549606/",
        "note": "African-enriched allele commonly absent from compact global panels.",
    },
    {
        "region": "Sub-Saharan Africa",
        "proxy": "Southern African review",
        "locus": "B",
        "allele": "HLA-B*81:01",
        "frequency": None,
        "resolution": "qualitative",
        "source_label": "Southern African perspective review",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4549606/",
        "note": "African-enriched allele commonly absent from compact global panels.",
    },
    {
        "region": "Latin America",
        "proxy": "Colombia 2022 registry",
        "locus": "A",
        "allele": "HLA-A*24:02",
        "frequency": 0.2087,
        "resolution": "exact",
        "source_label": "Colombian Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9869256/",
        "note": "Top Latin American proxy allele.",
    },
    {
        "region": "Latin America",
        "proxy": "Colombia 2022 registry",
        "locus": "A",
        "allele": "HLA-A*02:01",
        "frequency": 0.1611,
        "resolution": "exact",
        "source_label": "Colombian Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9869256/",
        "note": "Common Latin American proxy allele.",
    },
    {
        "region": "Latin America",
        "proxy": "Colombia 2022 registry",
        "locus": "A",
        "allele": "HLA-A*01:01",
        "frequency": 0.0706,
        "resolution": "exact",
        "source_label": "Colombian Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9869256/",
        "note": "Common Latin American proxy allele.",
    },
    {
        "region": "Latin America",
        "proxy": "Colombia 2022 registry",
        "locus": "A",
        "allele": "HLA-A*03:01",
        "frequency": 0.0683,
        "resolution": "exact",
        "source_label": "Colombian Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9869256/",
        "note": "Common Latin American proxy allele.",
    },
    {
        "region": "Latin America",
        "proxy": "Colombia 2022 registry",
        "locus": "A",
        "allele": "HLA-A*29:02",
        "frequency": 0.0522,
        "resolution": "exact",
        "source_label": "Colombian Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9869256/",
        "note": "Latin America-relevant allele worth adding in extended panels.",
    },
    {
        "region": "Latin America",
        "proxy": "Colombia 2022 registry",
        "locus": "B",
        "allele": "HLA-B*35:01",
        "frequency": 0.0769,
        "resolution": "proxy_group",
        "source_label": "Colombian Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9869256/",
        "note": "Representative B*35 family allele; top exact Colombian allele is B*35:43.",
    },
    {
        "region": "Latin America",
        "proxy": "Colombia 2022 registry",
        "locus": "B",
        "allele": "HLA-B*40:02",
        "frequency": 0.0718,
        "resolution": "exact",
        "source_label": "Colombian Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9869256/",
        "note": "Latin America-relevant B allele worth adding in extended panels.",
    },
    {
        "region": "Latin America",
        "proxy": "Colombia 2022 registry",
        "locus": "B",
        "allele": "HLA-B*44:03",
        "frequency": 0.0607,
        "resolution": "exact",
        "source_label": "Colombian Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9869256/",
        "note": "Common Latin American B allele.",
    },
    {
        "region": "Latin America",
        "proxy": "Colombia 2022 registry",
        "locus": "B",
        "allele": "HLA-B*07:02",
        "frequency": 0.0536,
        "resolution": "exact",
        "source_label": "Colombian Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9869256/",
        "note": "Common Latin American B allele.",
    },
    {
        "region": "Latin America",
        "proxy": "Colombia 2022 registry",
        "locus": "C",
        "allele": "HLA-C*04:01",
        "frequency": 0.1540,
        "resolution": "exact",
        "source_label": "Colombian Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9869256/",
        "note": "Top Latin American C allele.",
    },
    {
        "region": "Latin America",
        "proxy": "Colombia 2022 registry",
        "locus": "C",
        "allele": "HLA-C*01:02",
        "frequency": 0.1049,
        "resolution": "exact",
        "source_label": "Colombian Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9869256/",
        "note": "Common Latin American C allele.",
    },
    {
        "region": "Latin America",
        "proxy": "Colombia 2022 registry",
        "locus": "C",
        "allele": "HLA-C*07:02",
        "frequency": 0.1044,
        "resolution": "exact",
        "source_label": "Colombian Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9869256/",
        "note": "Common Latin American C allele.",
    },
    {
        "region": "Latin America",
        "proxy": "Colombia 2022 registry",
        "locus": "C",
        "allele": "HLA-C*07:01",
        "frequency": 0.0893,
        "resolution": "exact",
        "source_label": "Colombian Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9869256/",
        "note": "Common Latin American C allele.",
    },
    {
        "region": "Latin America",
        "proxy": "Colombia 2022 registry",
        "locus": "C",
        "allele": "HLA-C*03:04",
        "frequency": 0.0805,
        "resolution": "exact",
        "source_label": "Colombian Bone Marrow Registry",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC9869256/",
        "note": "Common Latin American C allele.",
    },
]


REGION_POPULATIONS: dict[str, float] = {
    "Europe": 743.9,
    "MENA / Arab": 599.9,
    "East Asia": 1_603.2,
    "Southeast Asia": 704.8,
    "South Asia": 2_076.8,
    "Latin America": 672.1,
    "Sub-Saharan Africa": 1_311.5,
}


def region_allele_frequencies() -> pd.DataFrame:
    """Return a DataFrame of per-region HLA allele frequencies.

    Each row corresponds to one entry in :data:`REGION_PRIORITY_ROWS`.
    """
    return pd.DataFrame(REGION_PRIORITY_ROWS)


def region_names() -> list[str]:
    """Return sorted unique region names from the priority table."""
    return sorted({row["region"] for row in REGION_PRIORITY_ROWS})
